-- MySQL Script generated by MySQL Workbench
-- Thứ năm, 16 Tháng mười một Năm 2017 21:50:12 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema legison
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema legison
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `legison` DEFAULT CHARACTER SET latin1 ;
USE `legison` ;

-- -----------------------------------------------------
-- Table `legison`.`Legals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legison`.`Legals` (
  `id` INT GENERATED ALWAYS AS (),
  `name` VARCHAR(45) NULL,
  `enforcer` VARCHAR(45) NULL,
  `effective` DATETIME NULL,
  `pass` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legison`.`Signers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legison`.`Signers` (
  `id` INT NOT NULL,
  `office` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legison`.`Sign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legison`.`Sign` (
  `id` INT NOT NULL,
  `date` DATETIME NULL,
  `Legal_id` INT NOT NULL,
  `Signer_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Signer_id`),
  INDEX `fk_Sign_Legal_idx` (`Legal_id` ASC),
  INDEX `fk_Sign_Signer1_idx` (`Signer_id` ASC),
  CONSTRAINT `fk_Sign_Legal`
    FOREIGN KEY (`Legal_id`)
    REFERENCES `legison`.`Legals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sign_Signer1`
    FOREIGN KEY (`Signer_id`)
    REFERENCES `legison`.`Signers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legison`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legison`.`Articles` (
  `id` INT NOT NULL,
  `header` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legison`.`Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legison`.`Topics` (
  `id` INT NOT NULL,
  `header` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `legison`.`Chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `legison`.`Chapters` (
  `id` INT NOT NULL,
  `header` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
